name: Trigger Repo B Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-b-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repo B Dispatch
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TARGET_REPO_TOKEN }}" \
          https://api.github.com/repos/<owner>/<repo-b>/dispatches \
          -d '{"event_type":"trigger-from-repo-a"}'
